name: Deploy Hugo Blog

on:
  push:
    branches:
      - main

jobs:
  build-hugo-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.141.0'
          extended: true

      - name: Build Blog Site
        run: hugo --gc --buildDrafts --minify --baseURL ${{ vars.SITE_BASE_URL }}

      - name: Upload Artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: hugo-blog
          path: public/
          if-no-files-found: error

    outputs:
      digest: ${{ steps.artifact-upload-step.outputs.artifact-digest }}
